crds:
  install: true
  keep: true

image:
  tag: "latest"
  pullPolicy: ""

telemetry:
  enabled: true

controllerImage: public.ecr.aws/anomalo/kelos/kelos-controller
claudeCodeImage: public.ecr.aws/anomalo/kelos/claude-code
codexImage: public.ecr.aws/anomalo/kelos/codex
geminiImage: public.ecr.aws/anomalo/kelos/gemini
opencodeImage: public.ecr.aws/anomalo/kelos/opencode
cursorImage: public.ecr.aws/anomalo/kelos/cursor
spawner:
  image: ghcr.io/kelos-dev/kelos-spawner
  resources:
    requests: ""
    limits: ""
tokenRefresher:
  image: ghcr.io/kelos-dev/kelos-token-refresher
  resources:
    requests: ""
    limits: ""
controller:
  resources:
    requests: {}
    limits: {}
webhookServer:
  image: public.ecr.aws/anomalo/kelos/kelos-webhook-server
  sources:
    github:
      enabled: false
      replicas: 1
      secretName: ""
    linear:
      enabled: false
      replicas: 1
      secretName: ""
  ingress:
    enabled: false
    className: ""
    host: ""
    annotations: {}
