#!/bin/bash
  set -euo pipefail                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                            
  echo "==> Installing Go tool dependencies..."                                                                                                                                                                                                                                                                                                                             
  make -C /workspaces/kelos controller-gen envtest yamlfmt shfmt 2>/dev/null || true                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            
  echo "==> Downloading Go modules..."                                                                                                                                                                                                                                                                                                                                      
  cd /workspaces/kelos && go mod download                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                            
  echo "==> Building kelos CLI..."                                                                                                                                                                                                                                                                                                                                          
  make -C /workspaces/kelos build WHAT=cmd/kelos 2>/dev/null || true                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            
  echo "==> Done! Run 'make test' to verify your setup."
